clientID:              ec762f06-7410-4f6d-aa82-969902c1836a
clientSecret:          6daf2cd7-4604-46c0-ab43-a645a6571d34
sslCertPath:           config/certs/apiclient_iat.pem
sslCaPath:             config/certs/apiclient_iat_chain.pem
sslKeyPath:            config/certs/apiclient_iat.key
sslKeyPass:            adpadp10
tokenServerURL:        https://iat-api.adp.com/auth/oauth/v2/token
disconnectURL:         https://iat-accounts.adp.com/auth/oauth/v2/logout
apiRequestURL:         https://iat-api.adp.com
baseAuthorizationURL:  https://iat-accounts.adp.com/auth/oauth/v2/authorize
redirectURL:           http://localhost:8889/callback
accessScope:           hr.workerInformationManagement.workerManagement.workerViewing.worker.read hr.workerInformationManagement.workerManagement.associateManagment.associate.read hr.workerInformationManagement.workerManagement.employeeManagement.employee.read,
responseType:          code
scope:                 openid
defaultexpiration:     3600
grantType:             authorization_code