clientID:       88a73992-07f2-4714-ab4b-de782acd9c4d
clientSecret:   a130adb7-aa51-49ac-9d02-0d4036b63541
sslCertPath:    config/certs/apiclient_iat.pem
sslCaPath:      config/certs/apiclient_iat_chain.pem
sslKeyPath:     config/certs/apiclient_iat.key
sslKeyPass:     adpadp10
tokenServerURL: https://iat-api.adp.com/auth/oauth/v2/token
disconnectURL:  https://iat-accounts.adp.com/auth/oauth/v2/logout
apiRequestURL:  https://iat-api.adp.com
responseType:   code
defaultexpiration: 3600
grantType:      client_credentials